export const data = {
  wd:[
    '你希望家园能给你带来什么',
    '你觉得你能给家园什么',
    '如果工作和学业冲突了你会怎么办',
    '你有加别的社团吗？如果时间冲突了怎么办？',
    '你对前端 / 后端有什么理解？你更喜欢前端or后端？'
  ],
  xz:[
    {
      question:'以下哪个不是前端使用的JS框架？',
      A:'Vue',
      B:'React',
      C:'JQuery',
      D:'Bootstrap',
      correct:['D'],
    },
    {
      question:'在前端范畴中，下列哪个不可以进行变量声明？',
      A:'let',
      B:'const',
      C:'import',
      D:'bool',
      correct:['D'],
    },
    {
      question:'下面哪个不是家园的部门',
      A:'研发部',
      B:'中心部',
      C:'产品部',
      D:'运营部',
      correct:['B'],
    }
  ],
  pd:[
    {
      question:'你会喝水吗',
      answer:true,
    },
    {
      question:'你会拉屎吗',
      answer:true,
    },
    {
      question:'你会上天入地吗',
      answer:false,
    }
  ],
  tk:[
    {
      question:'咸鱼必做的三件事是什么？',
      answer:['吃饭','睡觉','打豆豆'],
    },
    {
      question:'用啥听歌',
      answer:['酷狗','网易云','QQ音乐'],
    }
  ],
  zt:[
    {
      question:'给爷画一个一笔画！',
      imgSrc:'https://os.alipayobjects.com/rmsportal/QBnOOoLaAfKPirc.png'
    },
    {
      question:'画一个Banner！',
      imgSrc:'https://gw.alipayobjects.com/zos/rmsportal/JiqGstEfoWAOHiTxclqi.png'
    },
  ]
}